---
  # Title: LXDE on ubuntu
  #
  # Author: Luc Rutten
  # Version: 1.0
  # File: tasks/main.yml
  #
  # Description: Standardized lightweight gui for Ubuntu server
  

  - name: "Openbox | add noobslab/themes repository"
    apt_repository:
      repo: 'ppa:noobslab/themes'
      state: present

  - name: "Install additional packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - lubuntu-core
      - lxterminal
      - lxappearance
      - lxshortcut
      - compton
      - xrdp
      - firefox
      - windos-10-themes

  - name: "LXDE - Copy template pcmanfm.conf to /etc/xdg/pcmanfm/LXDE/pcmanfm.conf"
    template:
      src: pcmanfm.conf.j2
      dest: /etc/xdg/pcmanfm/LXDE/pcmanfm.conf
      owner: root
      group: root
      mode: 0755
      follow: yes

  - name: "LXDE - Copy template desktop.conf.j2 to /etc/xdg/lxsession/LXDE/desktop.conf"
    template:
      src: rc.xml.j2
      dest: /etc/xdg/lxsession/LXDE/desktop.conf
      owner: root
      group: root
      mode: 0755

  - name: "LightDM - Copy template rc.xml.j2 to /etc/xdg/openbox/LXDE/rc.xml"
    template:
      src: rc.xml.j2
      dest: /etc/xdg/openbox/LXDE/rc.xml
      owner: root
      group: root
      mode: 0755

  - name: "LightDM - Copy template 50-no-guest.conf.j2 to /etc/lightdm/lightdm.conf.d/50-no-guest.conf"
    template:
      src: 50-no-guest.conf.j2
      dest: /etc/lightdm/lightdm.conf.d/50-no-guest.conf
      owner: root
      group: root
      mode: 0755

  - name: "LightDM - Copy template 30_lubuntu.conf.j2 to  /etc/lightdm/lightdm-gtk-greeter.conf.d/30_lubuntu.conf"
    template:
      src: 30_lubuntu.conf.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf.d/30_lubuntu.conf
      owner: root
      group: root
      mode: 0755

  - name: "LightDM - Copy template 50-login-conf.j2 to /etc/lightdm/lightdm.conf.d/50-login-config.conf"
    template:
      src: 50-login-config.conf.j2
      dest: /etc/lightdm/lightdm.conf.d/50-login-config.conf
      owner: root
      group: root
      mode: 0755
 
  - name: "Panel - Copy file ubuntu-black-start.png to /usr/share/lubuntu/images/ubuntu-black-start.png "
    copy:
      src: ubuntu-black-start.png
      dest: /usr/share/lubuntu/images/ubuntu-black-start.png
      owner: root
      group: root
      mode: 0755
      
  - name: "Panel - Copy file ubuntu-black-start.png to /usr/share/lubuntu/images/panel_bg.png "
    copy:
      src: panel_bg.png
      dest: /usr/share/lubuntu/images/panel_bg.png
      owner: root
      group: root
      mode: 0755

  - name: "Panel - Copy template panel.j2 to /etc/xdg/lxpanel/LXDE/panels/panel"
    template:
      src: panel.j2
      dest: /etc/xdg/lxpanel/LXDE/panels/panel
      owner: root
      group: root
      mode: 0755

   

